import protocoloRouter from '../../../modules/user/routes/protocolos.routes';
import avisoRouter from '../../../modules/user/routes/avisos.routes';
import usersRouter from '../../../modules/user/routes/users.routes';
import { Router } from 'express';
import ataRouter from '../../../modules/user/routes/ata.routes';
import carteiraServicosRouter from '../../../modules/user/routes/carteiraServicos.routes';
import comissaoEmergenciaRouter from '../../../modules/user/routes/comissaoEmergencia.routes';
import lancamentosRouter from '../../../modules/user/routes/lancamentos';
import planoMunicipalDeSaudeRouter from '../../../modules/user/routes/planoMunicipalDeSaude.routes';
import programacaoAnual2022Router from '../../../modules/user/routes/programacaoAnual2022.routes';
import programacaoAnual2023Router from '../../../modules/user/routes/programacaoAnual2023.routes';
import programacaoAnual2024Router from '../../../modules/user/routes/ProgramacaoAnual2024.routes';
import programacaoAnual2025Router from '../../../modules/user/routes/ProgramacaoAnual2025.routes';
import rdqa1Router from '../../../modules/user/routes/rdqa1.routes';
import rdqa2Router from '../../../modules/user/routes/rdqa2.routes';
import rdqa3Router from '../../../modules/user/routes/rdqa3.routes';
import rag2022Router from '../../../modules/user/routes/rag2022.routes';
import rag2023Router from '../../../modules/user/routes/rag2023.routes';
import rag2024Router from '../../../modules/user/routes/rag2024.routes';
import rag2025Router from '../../../modules/user/routes/rag2025.routes';
import legislacaoRouter from '../../../modules/user/routes/legislacao.routes';

const routes = Router();

routes.use('/users', usersRouter);
routes.use('/avisos', avisoRouter);
routes.use('/protocolos', protocoloRouter);
routes.use('/ata', ataRouter);
routes.use('/carteiraservicos', carteiraServicosRouter);
routes.use('/comissaoemergencia', comissaoEmergenciaRouter);
routes.use('/lancamentos', lancamentosRouter);
routes.use('/planoMunicipalDeSaude', planoMunicipalDeSaudeRouter);
routes.use('/programacaoAnual2022', programacaoAnual2022Router);
routes.use('/programacaoAnual2023', programacaoAnual2023Router);
routes.use('/programacaoAnual2024', programacaoAnual2024Router);
routes.use('/programacaoAnual2025', programacaoAnual2025Router);
routes.use('/rdqa1', rdqa1Router);
routes.use('/rdqa2', rdqa2Router);
routes.use('/rdqa3', rdqa3Router);
routes.use('/rag2022', rag2022Router);
routes.use('/rag2023', rag2023Router);
routes.use('/rag2024', rag2024Router);
routes.use('/rag2025', rag2025Router);
routes.use('/legislacao', legislacaoRouter);

export default routes;
